<?php
/**
 * @file
 * Install, update and uninstall functions for the HybridAuth Bonus module.
 */

/**
 * Implements hook_uninstall().
 */
function hybridauth_bonus_uninstall() {
  config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_registration_role_choice');
  config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_registration_roles');
  config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_registration_roles_required');
  config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_registration_roles_multiple');
  config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_customize_widget_per_form');

  if (!function_exists('hybridauth_forms_list')) {
    module_load_include('module', 'hybridauth');
  }
  foreach (hybridauth_forms_list() as $form_id => $form_name) {
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_title_' . $form_id);
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_type_' . $form_id);
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_use_overlay_' . $form_id);
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_link_text_' . $form_id);
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_link_title_' . $form_id);
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_icon_pack_' . $form_id);
    config_clear('hybridauth_bonus.settings', 'hybridauth_bonus_widget_weight_' . $form_id);
  }
}

/**
 * Implements hook_update_N().
 */
function hybridauth_bonus_update_1000() {
  $config = config('hybridauth_bonus.settings');
  $config->set('hybridauth_bonus_registration_role_choice', update_variable_get('hybridauth_bonus_registration_role_choice', 'novalue'));
  $config->set('hybridauth_bonus_registration_roles', update_variable_get('hybridauth_bonus_registration_roles', 'dynamic value in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 120'));
  $config->set('hybridauth_bonus_registration_roles_required', update_variable_get('hybridauth_bonus_registration_roles_required', 'novalue'));
  $config->set('hybridauth_bonus_registration_roles_multiple', update_variable_get('hybridauth_bonus_registration_roles_multiple', '1'));
  $config->set('hybridauth_bonus_customize_widget_per_form', update_variable_get('hybridauth_bonus_customize_widget_per_form', 'novalue'));
  $config->set('hybridauth_bonus_widget_title_form_id', update_variable_get('hybridauth_bonus_widget_title_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 181'));
  $config->set('hybridauth_bonus_widget_type_form_id', update_variable_get('hybridauth_bonus_widget_type_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 182'));
  $config->set('hybridauth_bonus_widget_use_overlay_form_id', update_variable_get('hybridauth_bonus_widget_use_overlay_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 183'));
  $config->set('hybridauth_bonus_widget_link_text_form_id', update_variable_get('hybridauth_bonus_widget_link_text_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 184'));
  $config->set('hybridauth_bonus_widget_link_title_form_id', update_variable_get('hybridauth_bonus_widget_link_title_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 185'));
  $config->set('hybridauth_bonus_widget_icon_pack_form_id', update_variable_get('hybridauth_bonus_widget_icon_pack_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 186'));
  $config->set('hybridauth_bonus_widget_weight_form_id', update_variable_get('hybridauth_bonus_widget_weight_form_id', 'dynamic variable in file /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 187'));
  update_variable_del('hybridauth_bonus_registration_role_choice');
  update_variable_del('hybridauth_bonus_registration_roles');
  update_variable_del('hybridauth_bonus_registration_roles_required');
  update_variable_del('hybridauth_bonus_registration_roles_multiple');
  update_variable_del('hybridauth_bonus_customize_widget_per_form');
  update_variable_del('hybridauth_bonus_widget_title_form_id');
  update_variable_del('hybridauth_bonus_widget_type_form_id');
  update_variable_del('hybridauth_bonus_widget_use_overlay_form_id');
  update_variable_del('hybridauth_bonus_widget_link_text_form_id');
  update_variable_del('hybridauth_bonus_widget_link_title_form_id');
  update_variable_del('hybridauth_bonus_widget_icon_pack_form_id');
  update_variable_del('hybridauth_bonus_widget_weight_form_id');
}

/**
 * Implements hook_install().
 */
function hybridauth_bonus_install() {
  // Dynamically generated variable data was detected.
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 120
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 181
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 182
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 183
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 184
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 185
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 186
  // /hybridauth/hybridauth_bonus/hybridauth_bonus.module line 187
}
